### ISSUE TITLE
No Clear Log Function

### ISSUE THREAD

**Issue by wolewd** [trolit/unity-dev-console#1]
how to clear all the log? maybe you should add this feature.
my log keep spamming especially on movement script. oh and how to change my movement speed using this console? i put my movement script on my character prefabs

**Comment by trolit** [comment]
Hi @wolewd I will do that but if you want to have your solution quicker let me help you here :) 

> how to clear all the log?

Notice in the DevConsole script field called ConsoleText. It holds all data that you see in the console.

![Unity script in Inspector](https://user-images.githubusercontent.com/25982919/84589417-a8168c00-ae2e-11ea-8130-26c807b279a2.png)

So to clear your log you need to empty that field. How to do this? At first look I see two possible options. Create command and add to it's constructor parameter to pass text object reference from DevConsole to that command or even simpler, just use DevConsole Instance. Check second one first, it's much shorter :D 

### First option

1. Inside **CommandClearConsole** create extra variable, Text ConsoleText
2. Extend constructor with text parameter, e.g. Text _consoleTextRef.
3. Correct CreateCommand function
4. Inside constructor add line: ConsoleText = _consoleTextRef
5. In DevConsole create command: CommandClearConsole.CreateCommand(_consoleText)
⚠️ Don't forget to adjust properties inside CommandClearConsole constructor
 
When you done that, go to RunCommand() section. Clear command does not require any parameters so you need to check that data length equals 1. Then you verify that on data[0] position you have your command text e.g. "clear". If yes, you can do something like this:

```csharp
ConsoleText.text = string.Empty;      
```

This will clear **whole console including starting information**. If you want to leave that data you see after turning console on, the best option will be adding another variable of type string, ConsoleStartInfo that will store beginning text, example:

```csharp
ConsoleStartInfo = _consoleTextRef.text;
```

Then instead of this
```csharp
ConsoleText.text = string.Empty;  
```

You can do
```csharp
ConsoleText.text = ConsoleStartInfo;
```  

### Second option

If you want to use simpler, second solution:
1) Change _consoleText accessibility to public on DevConsole script
2) Create clear command
3) Inside RunCommand do all your checkings and then use that line:
```csharp
Instance._consoleText.text = ConsoleStartingInfo;
```


> how to change my movement speed using this console? i put my movement script on my character prefabs

You need to access that variable and overwrite it. One way you can do this is by using <a href="https://gamedev.stackexchange.com/a/116010">Singleton pattern</a> on your movement script. If you have instance, you will be able to create another command named "CommandSetSpeed" and inside RunCommand you would do something like this:

```csharp
// e.g. input setSpeed 0.5
var value = float.Parse(data[1]);
MyMovementScript.instance.speed = value;
```

If you have any questions feel free to ask:)

**Comment by wolewd** [comment]
thanks for your reply!
your explanations solve my problem
